# é¡¹ç›®æœåŠ¡å™¨é…ç½®ï¼ˆé»˜è®¤æ˜¯ä¸‹é¢çš„ï¼Œä¸å†™ä¹Ÿè¡Œï¼‰
# æµ‹è¯•ä¸?ä¸‹æ˜¯ä¸æ˜¯åœ¨åˆ†æ”?
server:
  port: 8080
  context-path: /


#==========logback start===================
#logging:
#    level:
#        com.lqm.controller.common.Test1Controller: 'off'

#==========logback end===================

#==========mysql redis druidç­‰start===================
spring:
  application:
    name: store
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/store?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    #æœ?å¤§æ´»è·ƒæ•°
    maxActive: 20
    #åˆå§‹åŒ–æ•°é‡?
    initialSize: 1
    #æœ?å¤§è¿æ¥ç­‰å¾…è¶…æ—¶æ—¶é—?
    maxWait: 60000
    #æ‰“å¼€PSCacheï¼Œå¹¶ä¸”æŒ‡å®šæ¯ä¸ªè¿æ¥PSCacheçš„å¤§å°?
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #é€šè¿‡connectionPropertieså±æ?§æ¥æ‰“å¼€mergeSqlåŠŸèƒ½ï¼›æ…¢SQLè®°å½•
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #é…ç½®ç›‘æ§ç»Ÿè®¡æ‹¦æˆªçš„filtersï¼Œå»æ‰åç›‘æ§ç•Œé¢sqlå°†æ— æ³•ç»Ÿè®?,'wall'ç”¨äºé˜²ç«å¢?
    filters: stat, wall, log4j
    tomcat:
      max-active: 150
      max-idle: 50
      min-idle: 10
      initial-size: 10
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 60000

  redis: # redisé…ç½®
    host: 127.0.0.1
    port: 6379
    timeout: 20000
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: -1



#è®¿é—®ï¼?127.0.0.1:8080/druid/login.html
#121.196.28.28:3306
#localhost:3306
druid:
  url: jdbc:mysql://127.0.0.1:3306/store
  username: admin
  password: 123456
  initial-size: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true

#========== end===================

#========== mybatis start===================
mybatis:
  # è‡ªåŠ¨æ‰«æ
  type-aliases-package: com.easylife.pojo
  configuration:
    # æ‰“å¼€å»¶è¿ŸåŠ è½½ çš„å¼€å…?
    lazy-loading-enabled: true
    # å°†ç§¯æåŠ è½½æ”¹ä¸ºæ¶ˆæåŠ è½½å³æŒ‰éœ€è¦åŠ è½?
    aggressive-lazy-loading: false
    # å¼?å¯äºŒçº§ç¼“å­?
    cache-enabled: true
    # æ”¯æŒé©¼å³°å‘½åæ³?
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.easylife.util.MyMapper
  not-empty: false
  identity: MYSQL


pagehelper:
  helperDialect: mysql
  # æ•°æ®åˆç†åŒ–ï¼štrueæ—¶åœ¨pageNum<1ä¼šæŸ¥è¯¢ç¬¬ä¸?é¡µï¼Œå¦‚æœpageNum>pagesä¼šæŸ¥è¯¢æœ€åä¸€é¡?,false:è¿”å›null
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

#========== mybatis end===================




